package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type FieldInfo struct {
	Name        string
	Type        string
	IsPointer   bool
	IsSlice     bool
	IsMap       bool
	IsStruct    bool
	IsPrimitive bool
	ElemType    string // для слайсов и мап
}

type StructInfo struct {
	Package string
	Name    string
	Fields  []FieldInfo
}

const resetTemplate = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset tool

package {{.Package}}

{{range .Structs}}
func (s *{{.Name}}) Reset() {
    if s == nil {
        return
    }

    {{range .Fields}}
    {{- if .IsPointer}}
    if s.{{.Name}} != nil {
        {{- if .IsStruct}}
        if resetter, ok := interface{}(s.{{.Name}}).(interface{ Reset() }); ok {
            resetter.Reset()
        }
        {{- else if .IsSlice}}
        s.{{.Name}} = (*s.{{.Name}})[:0]
        {{- else if .IsMap}}
        clear(*s.{{.Name}})
        {{- else}}
        *s.{{.Name}} = {{zeroValue .Type}}
        {{- end}}
    }
    {{- else if .IsSlice}}
    s.{{.Name}} = s.{{.Name}}[:0]
    {{- else if .IsMap}}
    clear(s.{{.Name}})
    {{- else if .IsStruct}}
    if resetter, ok := interface{}(s.{{.Name}}).(interface{ Reset() }); ok {
        resetter.Reset()
    }
    {{- else}}
    s.{{.Name}} = {{zeroValue .Type}}
    {{- end}}
    {{end}}
}
{{end}}
`

func zeroValue(typeName string) string {
	switch typeName {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "complex64", "complex128":
		return "0"
	case "string":
		return "\"\""
	case "bool":
		return "false"
	default:
		return typeName + "{}"
	}
}

func isPrimitiveType(typeName string) bool {
	primitives := map[string]bool{
		"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
		"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
		"float32": true, "float64": true,
		"complex64": true, "complex128": true,
		"string": true, "bool": true,
	}
	return primitives[typeName]
}

func parseType(expr ast.Expr) FieldInfo {
	var info FieldInfo

	switch t := expr.(type) {
	case *ast.Ident:
		info.Type = t.Name
		info.IsPrimitive = isPrimitiveType(t.Name)

	case *ast.StarExpr:
		info.IsPointer = true
		inner := parseType(t.X)
		info.Type = "*" + inner.Type
		info.IsPrimitive = inner.IsPrimitive
		info.IsSlice = inner.IsSlice
		info.IsMap = inner.IsMap
		info.IsStruct = inner.IsStruct
		info.ElemType = inner.ElemType

	case *ast.ArrayType:
		if t.Len == nil {
			info.IsSlice = true
			info.Type = "[]" + parseType(t.Elt).Type
			info.ElemType = parseType(t.Elt).Type
		}

	case *ast.MapType:
		info.IsMap = true
		keyType := parseType(t.Key).Type
		valueType := parseType(t.Value).Type
		info.Type = fmt.Sprintf("map[%s]%s", keyType, valueType)
		info.ElemType = valueType

	case *ast.SelectorExpr:
		info.Type = fmt.Sprintf("%s.%s", t.X.(*ast.Ident).Name, t.Sel.Name)
		info.IsPrimitive = false
		info.IsStruct = true
	}

	return info
}

func scanDir(dir string) ([]StructInfo, error) {
	var structs []StructInfo

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	for pkgName, pkg := range pkgs {
		for filename, file := range pkg.Files {
			// Пропускаем сгенерированные файлы
			if strings.HasSuffix(filename, ".gen.go") {
				continue
			}

			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					// Проверяем комментарий // generate:reset
					if !hasGenerateResetComment(typeSpec) {
						continue
					}

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					var fields []FieldInfo
					for _, field := range structType.Fields.List {
						if len(field.Names) == 0 {
							continue // анонимное поле, пропускаем
						}

						fieldName := field.Names[0].Name
						if ast.IsExported(fieldName) { //fieldName[0] < 'a' || fieldName[0] > 'z' {
							continue // экспортируемое поле, пропускаем
						}

						fieldInfo := parseType(field.Type)
						fieldInfo.Name = fieldName
						fields = append(fields, fieldInfo)
					}

					structs = append(structs, StructInfo{
						Package: pkgName,
						Name:    typeSpec.Name.Name,
						Fields:  fields,
					})
				}
			}
		}
	}

	return structs, nil
}

func hasGenerateResetComment(typeSpec *ast.TypeSpec) bool {
	if typeSpec.Doc == nil {
		return false
	}

	for _, comment := range typeSpec.Doc.List {
		if strings.Contains(comment.Text, "// generate:reset") {
			return true
		}
	}
	return false
}

func groupStructsByPackage(structs []StructInfo) map[string][]StructInfo {
	groups := make(map[string][]StructInfo)
	for _, s := range structs {
		groups[s.Package] = append(groups[s.Package], s)
	}
	return groups
}

func main() {
	// Сканируем все пакеты, начиная с текущей директории
	rootDir := "."
	allStructs := []StructInfo{}

	err := filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if !info.IsDir() {
			return nil
		}

		// Пропускаем директории migrations, .git и другие
		if strings.Contains(path, "profiles") ||
			strings.Contains(path, ".git") ||
			strings.Contains(path, "migrations") {
			return filepath.SkipDir
		}

		structs, err := scanDir(path)
		if err != nil {
			return err
		}

		allStructs = append(allStructs, structs...)
		return nil
	})

	if err != nil {
		panic(err)
	}

	// Группируем структуры по пакетам
	groups := groupStructsByPackage(allStructs)

	// Для каждого пакета генерируем файл reset.gen.go
	for pkg, structs := range groups {
		// Генерируем код
		tmpl, err := template.New("reset").Funcs(template.FuncMap{
			"zeroValue": zeroValue,
		}).Parse(resetTemplate)
		if err != nil {
			panic(err)
		}

		var buf bytes.Buffer
		err = tmpl.Execute(&buf, map[string]interface{}{
			"Package": pkg,
			"Structs": structs,
		})
		if err != nil {
			panic(err)
		}

		// Форматируем код
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			panic(err)
		}

		// Записываем в файл
		outputPath := filepath.Join(".", pkg, "reset.gen.go")
		err = os.WriteFile(outputPath, formatted, 0644)
		if err != nil {
			panic(err)
		}

		fmt.Printf("Generated reset methods for package %s (%d structs)\n", pkg, len(structs))
	}
}
